import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@repo/ui/globals.css";
import { Toaster } from "@repo/ui/components/sonner";
import { AppSidebar } from "@/components/app-sidebar";
import { Providers } from "@/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full overscroll-none" lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-full overscroll-none antialiased`}
      >
        <Providers>
          <AppSidebar />
          <main className="h-screen flex-1 overflow-hidden">{children}</main>
          <Toaster
            expand={false}
            offset={{
              bottom: 10,
              right: 10,
            }}
            toastOptions={{
              classNames: {
                toast: "!shadow-none !rounded-2xl !p-3 !pl-4",
              },
            }}
          />
        </Providers>
      </body>
    </html>
  );
}
